create table if not exists public.contact_submissions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  email text not null,
  phone text not null,
  country text not null,
  service text not null,
  message text,
  page_url text
);

alter table public.contact_submissions enable row level security;

create policy "Allow public contact form inserts"
on public.contact_submissions
for insert
to anon
with check (true);
