export interface Country {
  name: string;
  code: string;
  dialCode: string;
  flag: string;
  keywords?: string;
}

export const POPULAR_COUNTRIES: Country[] = [
  { name: "India", code: "IN", dialCode: "+91", flag: "🇮🇳", keywords: "bharat hindustan" },
  { name: "United States", code: "US", dialCode: "+1", flag: "🇺🇸", keywords: "usa america" },
  { name: "United Kingdom", code: "GB", dialCode: "+44", flag: "🇬🇧", keywords: "uk britain england" },
  { name: "United Arab Emirates", code: "AE", dialCode: "+971", flag: "🇦🇪", keywords: "uae dubai abu dhabi" },
  { name: "Canada", code: "CA", dialCode: "+1", flag: "🇨🇦" },
  { name: "Australia", code: "AU", dialCode: "+61", flag: "🇦🇺" },
  { name: "Singapore", code: "SG", dialCode: "+65", flag: "🇸🇬" },
  { name: "Saudi Arabia", code: "SA", dialCode: "+966", flag: "🇸🇦", keywords: "ksa riyadh" },
  { name: "Qatar", code: "QA", dialCode: "+974", flag: "🇶🇦", keywords: "doha" },
  { name: "Kuwait", code: "KW", dialCode: "+965", flag: "🇰🇼" },
  { name: "Oman", code: "OM", dialCode: "+968", flag: "🇴🇲", keywords: "muscat" },
  { name: "Bahrain", code: "BH", dialCode: "+973", flag: "🇧🇭", keywords: "manama" },
  { name: "Germany", code: "DE", dialCode: "+49", flag: "🇩🇪", keywords: "deutschland" },
];

export const ALL_COUNTRIES: Country[] = [
  { name: "Afghanistan", code: "AF", dialCode: "+93", flag: "🇦🇫" },
  { name: "Albania", code: "AL", dialCode: "+355", flag: "🇦🇱" },
  { name: "Algeria", code: "DZ", dialCode: "+213", flag: "🇩🇿" },
  { name: "Andorra", code: "AD", dialCode: "+376", flag: "🇦🇩" },
  { name: "Angola", code: "AO", dialCode: "+244", flag: "🇦🇴" },
  { name: "Argentina", code: "AR", dialCode: "+54", flag: "🇦🇷" },
  { name: "Armenia", code: "AM", dialCode: "+374", flag: "🇦🇲" },
  { name: "Australia", code: "AU", dialCode: "+61", flag: "🇦🇺" },
  { name: "Austria", code: "AT", dialCode: "+43", flag: "🇦🇹" },
  { name: "Azerbaijan", code: "AZ", dialCode: "+994", flag: "🇦🇿" },
  { name: "Bahamas", code: "BS", dialCode: "+1-242", flag: "🇧🇸" },
  { name: "Bahrain", code: "BH", dialCode: "+973", flag: "🇧🇭", keywords: "manama" },
  { name: "Bangladesh", code: "BD", dialCode: "+880", flag: "🇧🇩", keywords: "dhaka" },
  { name: "Barbados", code: "BB", dialCode: "+1-246", flag: "🇧🇧" },
  { name: "Belarus", code: "BY", dialCode: "+375", flag: "🇧🇾" },
  { name: "Belgium", code: "BE", dialCode: "+32", flag: "🇧🇪" },
  { name: "Belize", code: "BZ", dialCode: "+501", flag: "🇧🇿" },
  { name: "Benin", code: "BJ", dialCode: "+229", flag: "🇧🇯" },
  { name: "Bhutan", code: "BT", dialCode: "+975", flag: "🇧🇹" },
  { name: "Bolivia", code: "BO", dialCode: "+591", flag: "🇧🇴" },
  { name: "Bosnia and Herzegovina", code: "BA", dialCode: "+387", flag: "🇧🇦" },
  { name: "Botswana", code: "BW", dialCode: "+267", flag: "🇧🇼" },
  { name: "Brazil", code: "BR", dialCode: "+55", flag: "🇧🇷" },
  { name: "Brunei", code: "BN", dialCode: "+673", flag: "🇧🇳" },
  { name: "Bulgaria", code: "BG", dialCode: "+359", flag: "🇧🇬" },
  { name: "Cambodia", code: "KH", dialCode: "+855", flag: "🇰🇭" },
  { name: "Cameroon", code: "CM", dialCode: "+237", flag: "🇨🇲" },
  { name: "Canada", code: "CA", dialCode: "+1", flag: "🇨🇦" },
  { name: "Chile", code: "CL", dialCode: "+56", flag: "🇨🇱" },
  { name: "China", code: "CN", dialCode: "+86", flag: "🇨🇳" },
  { name: "Colombia", code: "CO", dialCode: "+57", flag: "🇨🇴" },
  { name: "Costa Rica", code: "CR", dialCode: "+506", flag: "🇨🇷" },
  { name: "Croatia", code: "HR", dialCode: "+385", flag: "🇭🇷" },
  { name: "Cyprus", code: "CY", dialCode: "+357", flag: "🇨🇾" },
  { name: "Czech Republic", code: "CZ", dialCode: "+420", flag: "🇨🇿" },
  { name: "Denmark", code: "DK", dialCode: "+45", flag: "🇩🇰" },
  { name: "Ecuador", code: "EC", dialCode: "+593", flag: "🇪🇨" },
  { name: "Egypt", code: "EG", dialCode: "+20", flag: "🇪🇬", keywords: "cairo" },
  { name: "Estonia", code: "EE", dialCode: "+372", flag: "🇪🇪" },
  { name: "Ethiopia", code: "ET", dialCode: "+251", flag: "🇪🇹" },
  { name: "Fiji", code: "FJ", dialCode: "+679", flag: "🇫🇯" },
  { name: "Finland", code: "FI", dialCode: "+358", flag: "🇫🇮" },
  { name: "France", code: "FR", dialCode: "+33", flag: "🇫🇷", keywords: "paris" },
  { name: "Georgia", code: "GE", dialCode: "+995", flag: "🇬🇪" },
  { name: "Germany", code: "DE", dialCode: "+49", flag: "🇩🇪", keywords: "deutschland berlin" },
  { name: "Ghana", code: "GH", dialCode: "+233", flag: "🇬🇭" },
  { name: "Greece", code: "GR", dialCode: "+30", flag: "🇬🇷", keywords: "athens" },
  { name: "Hong Kong", code: "HK", dialCode: "+852", flag: "🇭🇰" },
  { name: "Hungary", code: "HU", dialCode: "+36", flag: "🇭🇺" },
  { name: "Iceland", code: "IS", dialCode: "+354", flag: "🇮🇸" },
  { name: "India", code: "IN", dialCode: "+91", flag: "🇮🇳", keywords: "bharat hindustan delhi mumbai bangalore" },
  { name: "Indonesia", code: "ID", dialCode: "+62", flag: "🇮🇩", keywords: "jakarta bali" },
  { name: "Iran", code: "IR", dialCode: "+98", flag: "🇮🇷" },
  { name: "Iraq", code: "IQ", dialCode: "+964", flag: "🇮🇶" },
  { name: "Ireland", code: "IE", dialCode: "+353", flag: "🇮🇪", keywords: "dublin" },
  { name: "Israel", code: "IL", dialCode: "+972", flag: "🇮🇱", keywords: "tel aviv" },
  { name: "Italy", code: "IT", dialCode: "+39", flag: "🇮🇹", keywords: "rome milan" },
  { name: "Jamaica", code: "JM", dialCode: "+1-876", flag: "🇯🇲" },
  { name: "Japan", code: "JP", dialCode: "+81", flag: "🇯🇵", keywords: "tokyo" },
  { name: "Jordan", code: "JO", dialCode: "+962", flag: "🇯🇴", keywords: "amman" },
  { name: "Kazakhstan", code: "KZ", dialCode: "+7", flag: "🇰🇿" },
  { name: "Kenya", code: "KE", dialCode: "+254", flag: "🇰🇪", keywords: "nairobi" },
  { name: "Kuwait", code: "KW", dialCode: "+965", flag: "🇰🇼" },
  { name: "Latvia", code: "LV", dialCode: "+371", flag: "🇱🇻" },
  { name: "Lebanon", code: "LB", dialCode: "+961", flag: "🇱🇧", keywords: "beirut" },
  { name: "Lithuania", code: "LT", dialCode: "+370", flag: "🇱🇹" },
  { name: "Luxembourg", code: "LU", dialCode: "+352", flag: "🇱🇺" },
  { name: "Malaysia", code: "MY", dialCode: "+60", flag: "🇲🇾", keywords: "kuala lumpur" },
  { name: "Maldives", code: "MV", dialCode: "+960", flag: "🇲🇻" },
  { name: "Malta", code: "MT", dialCode: "+356", flag: "🇲🇹" },
  { name: "Mauritius", code: "MU", dialCode: "+230", flag: "🇲🇺" },
  { name: "Mexico", code: "MX", dialCode: "+52", flag: "🇲🇽" },
  { name: "Monaco", code: "MC", dialCode: "+377", flag: "🇲🇨" },
  { name: "Morocco", code: "MA", dialCode: "+212", flag: "🇲🇦" },
  { name: "Myanmar", code: "MM", dialCode: "+95", flag: "🇲🇲" },
  { name: "Nepal", code: "NP", dialCode: "+977", flag: "🇳🇵", keywords: "kathmandu" },
  { name: "Netherlands", code: "NL", dialCode: "+31", flag: "🇳🇱", keywords: "amsterdam holland" },
  { name: "New Zealand", code: "NZ", dialCode: "+64", flag: "🇳🇿", keywords: "auckland" },
  { name: "Nigeria", code: "NG", dialCode: "+234", flag: "🇳🇬", keywords: "lagos" },
  { name: "Norway", code: "NO", dialCode: "+47", flag: "🇳🇴", keywords: "oslo" },
  { name: "Oman", code: "OM", dialCode: "+968", flag: "🇴🇲", keywords: "muscat" },
  { name: "Pakistan", code: "PK", dialCode: "+92", flag: "🇵🇰", keywords: "karachi lahore" },
  { name: "Panama", code: "PA", dialCode: "+507", flag: "🇵🇦" },
  { name: "Peru", code: "PE", dialCode: "+51", flag: "🇵🇪" },
  { name: "Philippines", code: "PH", dialCode: "+63", flag: "🇵🇭", keywords: "manila" },
  { name: "Poland", code: "PL", dialCode: "+48", flag: "🇵🇱", keywords: "warsaw" },
  { name: "Portugal", code: "PT", dialCode: "+351", flag: "🇵🇹", keywords: "lisbon" },
  { name: "Qatar", code: "QA", dialCode: "+974", flag: "🇶🇦", keywords: "doha" },
  { name: "Romania", code: "RO", dialCode: "+40", flag: "🇷🇴" },
  { name: "Russia", code: "RU", dialCode: "+7", flag: "🇷🇺", keywords: "moscow" },
  { name: "Saudi Arabia", code: "SA", dialCode: "+966", flag: "🇸🇦", keywords: "ksa riyadh jeddah" },
  { name: "Serbia", code: "RS", dialCode: "+381", flag: "🇷🇸" },
  { name: "Singapore", code: "SG", dialCode: "+65", flag: "🇸🇬" },
  { name: "Slovakia", code: "SK", dialCode: "+421", flag: "🇸🇰" },
  { name: "Slovenia", code: "SI", dialCode: "+386", flag: "🇸🇮" },
  { name: "South Africa", code: "ZA", dialCode: "+27", flag: "🇿🇦", keywords: "johannesburg cape town" },
  { name: "South Korea", code: "KR", dialCode: "+82", flag: "🇰🇷", keywords: "seoul" },
  { name: "Spain", code: "ES", dialCode: "+34", flag: "🇪🇸", keywords: "madrid barcelona" },
  { name: "Sri Lanka", code: "LK", dialCode: "+94", flag: "🇱🇰", keywords: "colombo" },
  { name: "Sweden", code: "SE", dialCode: "+46", flag: "🇸🇪", keywords: "stockholm" },
  { name: "Switzerland", code: "CH", dialCode: "+41", flag: "🇨🇭", keywords: "zurich geneva" },
  { name: "Taiwan", code: "TW", dialCode: "+886", flag: "🇹🇼" },
  { name: "Tanzania", code: "TZ", dialCode: "+255", flag: "🇹🇿" },
  { name: "Thailand", code: "TH", dialCode: "+66", flag: "🇹🇭", keywords: "bangkok" },
  { name: "Tunisia", code: "TN", dialCode: "+216", flag: "🇹🇳" },
  { name: "Turkey", code: "TR", dialCode: "+90", flag: "🇹🇷", keywords: "istanbul ankara turkiye" },
  { name: "Uganda", code: "UG", dialCode: "+256", flag: "🇺🇬" },
  { name: "Ukraine", code: "UA", dialCode: "+380", flag: "🇺🇦", keywords: "kyiv" },
  { name: "United Arab Emirates", code: "AE", dialCode: "+971", flag: "🇦🇪", keywords: "uae dubai abu dhabi sharjah" },
  { name: "United Kingdom", code: "GB", dialCode: "+44", flag: "🇬🇧", keywords: "uk britain england london" },
  { name: "United States", code: "US", dialCode: "+1", flag: "🇺🇸", keywords: "usa america new york california texas" },
  { name: "Uruguay", code: "UY", dialCode: "+598", flag: "🇺🇾" },
  { name: "Uzbekistan", code: "UZ", dialCode: "+998", flag: "🇺🇿" },
  { name: "Venezuela", code: "VE", dialCode: "+58", flag: "🇻🇪" },
  { name: "Vietnam", code: "VN", dialCode: "+84", flag: "🇻🇳", keywords: "hanoi ho chi minh" },
  { name: "Zambia", code: "ZM", dialCode: "+260", flag: "🇿🇲" },
  { name: "Zimbabwe", code: "ZW", dialCode: "+263", flag: "🇿🇼" },
];

export const DEFAULT_COUNTRY: Country = {
  name: "India",
  code: "IN",
  dialCode: "+91",
  flag: "🇮🇳",
  keywords: "bharat hindustan delhi mumbai bangalore",
};
